:bug: OverflowError: int too large to convert to float
https://github.com/tubone24/tech_blog_spider/runs/3017554640?check_suite_focus=true

```
Run python3 src/main.py
start tech blog spider
Traceback (most recent call last):
  File "src/main.py", line 63, in <module>
    main()
  File "src/main.py", line 59, in main
    github_action.run()
  File "/home/runner/work/tech_blog_spider/tech_blog_spider/src/controller/github_action.py", line 16, in run
    last_published_date = self.entry_usecase.post_unread_entries(feed)
  File "/home/runner/work/tech_blog_spider/tech_blog_spider/src/interactor/entry_usecase.py", line 18, in post_unread_entries
    entries = self.entry_repository.get_all_entries(feed.url)
  File "/home/runner/work/tech_blog_spider/tech_blog_spider/src/repository/entry_repository.py", line 38, in get_all_entries
    for x in self.keyword_driver.get_keyword_list(entry["text"], language)
  File "/home/runner/work/tech_blog_spider/tech_blog_spider/src/driver/keyword_driver.py", line 22, in get_keyword_list
    term_imp = self._extract_keyword_english(text)
  File "/home/runner/work/tech_blog_spider/tech_blog_spider/src/driver/keyword_driver.py", line 45, in _extract_keyword_english
    average_rate=1,
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/termextract/core.py", line 51, in score_lr
    average_rate, lr_mode)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/termextract/core.py", line 82, in _score_lr_dict
    importance = importance ** (1 / (2 * average_rate * count))
OverflowError: int too large to convert to float
Error: Process completed with exit code 1.
```